#' Make shortcut functions for data objects in bcmaps.rdata
#'
#' This generates a `shortcuts.R` file in the `R` directory, with function definitions
#' and roxygen blocks for each data object in `bcmaps.rdata`. This ensures that each
#' data object in `bcmaps.rdata` can be accessed directly from `bcmaps` by a
#' function such as `bc_bound()`, or `airzones("sp")`.
#'
#' Run this function each time you add a new data object.
#'
#' @param file the R file where the shortcut file is. Default "R/shortcuts.R"
#'
#' @return TRUE (invisibly)
#'
make_shortcuts <- function(file = "R/shortcuts.R") {

  if (!requireNamespace("bcmaps") || !requireNamespace("bcmaps.rdata") ||
      !requireNamespace("bcgovr") || !requireNamespace("glue")) {
    stop("bcmaps, bcmaps.rdata, bcgovr, and glue all need to be installed.")
  }

  available_layers <- bcmaps::available_layers()

  cat(
    glue("
      #############################################################
      # This file is automatically generated by running the function
      # bcmaps:::make_shortcuts(). Do not edit by hand.
      #############################################################

      "
    ),
    file = file, append = FALSE)

  for (i in seq_len(nrow(available_layers))) {
    fn_name <- available_layers[i, "Item"]
    fn_title <- available_layers[i, "Title"]

    fn_defn <- glue("

         #' {fn_title}
         #'
         #' @param class what class you want the object in? `\"sf\"` (default) or `\"sp\"`.
         #'
         #' @return The spatial layer in the desired class
         #'
         #' @details See [bcmaps.rdata::{fn_name}] for details.
         #'
         #' @export
         {fn_name} <- function(class = 'sf') {{
            get_layer('{fn_name}', class = class)
         }}

         ")
    cat(as.character(fn_defn), file = file, append = TRUE)
  }

  bcgovr::add_license_header(file)

  invisible(TRUE)
}
