# Copyright 2017 Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.

#' Make shortcut functions for data objects in bcmaps.rdata
#'
#' This generates a `shortcuts.R` file in the `R` directory, with function definitions
#' and roxygen blocks for each data object in `bcmaps.rdata`. This ensures that each
#' data object in `bcmaps.rdata` can be accessed directly from `bcmaps` by a
#' function such as `bc_bound()`, or `airzones("sp")`.
#'
#' Run this function each time you add a new data object.
#'
#' @param file the R file where the shortcut file is. Default "R/shortcuts.R"
#'
#' @examples
#' \dontrun{
#' make_shortcut()
#' }
#'
#' @return TRUE (invisibly)
make_shortcuts <- function(file = "R/shortcuts.R") {

  if (!requireNamespace("bcmaps") || !requireNamespace("bcmaps.rdata") ||
      !requireNamespace("glue")) {
    stop("bcmaps, bcmaps.rdata, and glue all need to be installed.")
  }

  available_layers <- bcmaps::available_layers()

  cat(
    glue::glue("
      #############################################################
      # This file is automatically generated by running the function
      # bcmaps:::make_shortcuts(). Do not edit by hand.
      #############################################################

      "
    ),
    file = file, append = FALSE)

  for (i in seq_len(nrow(available_layers))) {
    fn_name <- available_layers[i, "Item"]
    fn_title <- available_layers[i, "Title"]

    fn_defn <- glue::glue("

         roxygen_blocker#' {fn_title}
         roxygen_blocker#'
         roxygen_blocker#' You must have the `bcmaps.rdata` package installed to use this function.
         roxygen_blocker#'
         roxygen_blocker#' @param class what class you want the object in? `\"sf\"` (default) or `\"sp\"`.
         roxygen_blocker#'
         roxygen_blocker#' @return The spatial layer of `{fn_name}` in the desired class
         roxygen_blocker#'
         roxygen_blocker#' @details Type `?bcmaps.rdata::{fn_name}` for details.
         roxygen_blocker#'
         roxygen_blocker#' @examples
         roxygen_blocker#' \\dontrun{{
         roxygen_blocker#' my_layer <- {fn_name}()
         roxygen_blocker#' my_layer_sp <- {fn_name}(class = 'sp')
         roxygen_blocker#' }}
         roxygen_blocker#'
         roxygen_blocker#' @export
         {fn_name} <- function(class = 'sf') {{
            get_layer('{fn_name}', class = class)
         }}

         ")
    fn_defn <- gsub("roxygen_blocker", "", fn_defn)
    cat(fn_defn, file = file, append = TRUE)
    message("Success! Shortcut function for '", fn_name, "' added to ", file)
  }

  add_license_header(file)
  message("Don't forget to run devtools::document to rebuild documentation.")

  invisible(TRUE)
}
