# Copyright 2017 Province of British Columbia
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.


#############################################################
# This file is automatically generated by running the function
# bcmaps:::make_shortcuts(). Do not edit by hand.
#############################################################

#' British Columbia Air Zones
#'
#' @param class what class you want the object in? `"sf"` (default) or `"sp"`.
#'
#' @return The spatial layer in the desired class
#'
#' @details See [bcmaps.rdata::airzones] for details.
#'
#' @export
airzones <- function(class = 'sf') {
   get_layer('airzones', class = class)
}

#' BC Boundary
#'
#' @param class what class you want the object in? `"sf"` (default) or `"sp"`.
#'
#' @return The spatial layer in the desired class
#'
#' @details See [bcmaps.rdata::bc_bound] for details.
#'
#' @export
bc_bound <- function(class = 'sf') {
   get_layer('bc_bound', class = class)
}

#' BC Boundary - High Resolution
#'
#' @param class what class you want the object in? `"sf"` (default) or `"sp"`.
#'
#' @return The spatial layer in the desired class
#'
#' @details See [bcmaps.rdata::bc_bound_hres] for details.
#'
#' @export
bc_bound_hres <- function(class = 'sf') {
   get_layer('bc_bound_hres', class = class)
}

#' British Columbia Ecoprovinces
#'
#' @param class what class you want the object in? `"sf"` (default) or `"sp"`.
#'
#' @return The spatial layer in the desired class
#'
#' @details See [bcmaps.rdata::ecoprovinces] for details.
#'
#' @export
ecoprovinces <- function(class = 'sf') {
   get_layer('ecoprovinces', class = class)
}

#' British Columbia Ecoregions
#'
#' @param class what class you want the object in? `"sf"` (default) or `"sp"`.
#'
#' @return The spatial layer in the desired class
#'
#' @details See [bcmaps.rdata::ecoregions] for details.
#'
#' @export
ecoregions <- function(class = 'sf') {
   get_layer('ecoregions', class = class)
}

#' Polygons delineating British Columbia's developed ground water aquifers (that have been mapped). Most aquifer boundaries are delineated based on geology, hydrology and topographic information. Some aquifer boundaries stop at the border of BC mapsheet boundaries due to resource or data constraints at the time of mapping.
#'
#' @param class what class you want the object in? `"sf"` (default) or `"sp"`.
#'
#' @return The spatial layer in the desired class
#'
#' @details See [bcmaps.rdata::gw_aquifers] for details.
#'
#' @export
gw_aquifers <- function(class = 'sf') {
   get_layer('gw_aquifers', class = class)
}

#' British Columbia Ecoregions
#'
#' @param class what class you want the object in? `"sf"` (default) or `"sp"`.
#'
#' @return The spatial layer in the desired class
#'
#' @details See [bcmaps.rdata::municipalities] for details.
#'
#' @export
municipalities <- function(class = 'sf') {
   get_layer('municipalities', class = class)
}

#' British Columbia Ecoregions
#'
#' @param class what class you want the object in? `"sf"` (default) or `"sp"`.
#'
#' @return The spatial layer in the desired class
#'
#' @details See [bcmaps.rdata::regional_districts] for details.
#'
#' @export
regional_districts <- function(class = 'sf') {
   get_layer('regional_districts', class = class)
}

#' British Columbia watercourses at 1:15M scale.
#'
#' @param class what class you want the object in? `"sf"` (default) or `"sp"`.
#'
#' @return The spatial layer in the desired class
#'
#' @details See [bcmaps.rdata::watercourses_15M] for details.
#'
#' @export
watercourses_15M <- function(class = 'sf') {
   get_layer('watercourses_15M', class = class)
}

#' British Columbia watercourses at 1:5M scale.
#'
#' @param class what class you want the object in? `"sf"` (default) or `"sp"`.
#'
#' @return The spatial layer in the desired class
#'
#' @details See [bcmaps.rdata::watercourses_5M] for details.
#'
#' @export
watercourses_5M <- function(class = 'sf') {
   get_layer('watercourses_5M', class = class)
}
